---
# Source: cluster-base/charts/cert-manager/templates/cainjector-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cluster-base-cert-manager-cainjector
  namespace: cluster-core
  labels:
    app: cainjector
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/instance: cluster-base
    app.kubernetes.io/component: "cainjector"
    app.kubernetes.io/version: "v1.16.1"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.16.1
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9402
    name: http-metrics
  selector:
    app.kubernetes.io/name: cainjector
    app.kubernetes.io/instance: cluster-base
    app.kubernetes.io/component: "cainjector"
