---
# Source: cluster-base/charts/cert-manager/templates/webhook-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: cluster-base-cert-manager-webhook
  namespace: cluster-core
  labels:
    app: webhook
    app.kubernetes.io/name: webhook
    app.kubernetes.io/instance: cluster-base
    app.kubernetes.io/component: "webhook"
    app.kubernetes.io/version: "v1.16.1"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: cert-manager-v1.16.1
