apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-core
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/mikeivanichev/cluster-core"
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
