apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: ztunnel
    repo: https://istio-release.storage.googleapis.com/charts
    releaseName: ztunnel
    namespace: istio-system
    version: "1.23.0"
