apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ztunnel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: istio-system
  project: default
  source:
    repoURL: "https://github.com/MikeIvanichev/cluster-core.git"
    targetRevision: HEAD
    path: app-definitions/istio-ztunnel/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
