apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ztunnel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: default
  source:
    chart: ztunnel
    repoURL: "https://istio-release.storage.googleapis.com/charts"
    targetRevision: "1.23.0"
    helm:
      valuesObject:
        resources:
          requests:
            memory: 128Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
