---
# Source: cilium/charts/cilium/templates/hubble/tls-certmanager/server-secret.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-server-certs
  namespace: cluster-core
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: hubble-ca-issuer
  secretName: hubble-server-certs
  commonName: "*.default.hubble-grpc.cilium.io"
  dnsNames:
  - "*.default.hubble-grpc.cilium.io"
  duration: 26280h0m0s
  privateKey:
    rotationPolicy: Always
  isCA: false
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
