---
# Source: istio/charts/base/templates/reader-serviceaccount.yaml
# This singleton service account aggregates reader permissions for the revisions in a given cluster
# ATM this is a singleton per cluster with Istio installed, and is not revisioned. It maybe should be,
# as otherwise compromising the token for this SA would give you access to *every* installed revision.
# Should be used for remote secret creation.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-reader-service-account
  namespace: istio-system
  labels:
    app: istio-reader
    release: istio
    app.kubernetes.io/name: "istio-reader"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/instance: "istio"
    app.kubernetes.io/part-of: "istio"
    app.kubernetes.io/version: "1.24.0-alpha.0"
    helm.sh/chart: base-1.24.0-alpha.0
