apiVersion: apps/v1
kind: Deployment
metadata:
  name: ztunnel
  namespace: istio-system
spec:
  template:
    spec:
      containers:
        - name: istio-proxy
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
      volumes:
        - name: cni-ztunnel-sock-dir
          hostPath:
            path: /sys/fs/cgroup
