apiVersion: v2
name: cluster-base
version: 0.0.2
type: application

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io/

  - name: cilium
    repository: https://helm.cilium.io/

  - name: base
    repository: https://istio-release.storage.googleapis.com/charts
    alias: istio-base
    condition: istio.enabled

  - name: cni
    repository: https://istio-release.storage.googleapis.com/charts
    alias: istio-cni
    condition: istio.enabled

  - name: istiod
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled

  - name: ztunnel
    repository: https://istio-release.storage.googleapis.com/charts
    condition: istio.enabled
