---
# Source: cilium/templates/hubble-ca-issuer.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: hubble-selfsigned-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: hubble-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
# Source: cilium/templates/hubble-ca-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: hubble-selfsigned-issuer
spec:
  selfSigned: {}
---
# Source: cilium/templates/hubble-ca-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: hubble-ca-issuer
spec:
  ca:
    secretName: root-secret
