apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/MikeIvanichev/cluster-core"
    targetRevision: HEAD
    path: app-definitions/argocd
  destination:
    name: in-cluster
    namespace: argocd
