apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: "https://github.com/MikeIvanichev/cluster-core.git"
      ref: cilium-values
      targetRevision: HEAD
      path: app-definitions/cilium/
    - repoURL: "https://helm.cilium.io/"
      chart: cilium
      targetRevision: "v1.16.1"
      helm:
        valueFiles:
          - $cilium-values/values.yaml
        parameters:
          - name: installCRDs
            value: "true"
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
