apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://helm.cilium.io/"
    chart: cilium
    targetRevision: "v1.16.1"
    helm:
      parameters:
        - name: installCRDs
          value: "true"
        - name: "cluster.name"
          value: core
        - name: "ipam.mode"
          value: kubernetes
        - name: kubeProxyReplacement
          value: "true"
        - name: "securityContext.capabilities.ciliumAgent"
          value: "{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
        - name: "securityContext.capabilities.cleanCiliumState"
          value: "{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
        - name: "cgroup.autoMount.enabled"
          value: "false"
        - name: "cgroup.hostRoot"
          value: "/sys/fs/cgroup"
        - name: k8sServiceHost
          value: localhost
        - name: k8sServicePort
          value: "7445"
        - name: "operator.replicas"
          value: "1" # While we are not HA
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: hubble-ca-cert
      jsonPointers:
        - /data/ca.crt
    - group: ""
      kind: Secret
      name: hubble-relay-client-certs
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
    - group: ""
      kind: Secret
      name: hubble-server-certs
      jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated: {}
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
