apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://helm.cilium.io/"
    chart: cilium
    targetRevision: "v1.16.1"
    helm:
      valuesObject:
        installCRDs: true
        kubeProxyReplacement: true
        k8sServiceHost: localhost
        k8sServicePort: 7445
        cni:
          exclusive: false
        operator:
          replicas: 1
        socketLB:
          hostNamespaceOnly: true
        cluster:
          name: core
        ipam:
          mode: kubernetes

        securityContext:
          capabilities:
            ciliumAgent:
              - CHOWN
              - KILL
              - NET_ADMIN
              - NET_RAW
              - IPC_LOCK
              - SYS_ADMIN
              - SYS_RESOURCE
              - DAC_OVERRIDE
              - FOWNER
              - SETGID
              - SETUID
            cleanCiliumState:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RESOURCE

        cgroup:
          hostRoot: /sys/fs/cgroup
          autoMount:
            enabled: false

        hubble:
          enabled: true
          tls:
            enabled: true
            auto:
              enabled: true
              method: certmanager
              certValidityDuration: 1095
              certManagerIssuerRef:
                group: cert-manager.io
                kind: ClusterIssuer
                name: hubble-ca-issuer
          relay:
            enabled: true
          ui:
            enabled: true
          metrics:
            enabled:
              - dns
              - drop
              - tcp
              - flow
              - port-distribution
              - icmp
              - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction

  ignoreDifferences:
    - jsonPointers:
        - /data/ca.crt
      kind: ConfigMap
      name: hubble-ca-cert
    - jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
      kind: Secret
      name: hubble-relay-client-certs
    - jsonPointers:
        - /data/ca.crt
        - /data/tls.crt
        - /data/tls.key
      kind: Secret
      name: hubble-server-certs
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
