apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubelet-serving-cert-approver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: kubelet-serving-cert-approver
  source:
    repoURL: "https://github.com/alex1989hu/kubelet-serving-cert-approver.git"
    path: deploy/standalone-install.yaml
    targetRevision: "e41795fb0cebb5aed2a20bc3e53294c485524505"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
