apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-connect
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cluster-auth
  source:
    repoURL: https://1password.github.io/connect-helm-charts/
    chart: connect
    targetRevision: "1.15.1"
    helm:
      parameters:
        - name: installCRDs
          value: "true"

      valuesObject:
        connect:
          create: true
          replicas: 1
          credentialsName: op-credentials
          credentialsKey: 1password-credentials.json
        operator:
          create: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      annotations:
        istio.io/dataplane-mode: ambient
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
