cilium:
  hubble:
    enabled: true
    tls:
      enabled: true
      auto:
        enabled: true
        method: certmanager
        certValidityDuration: 1095
        certManagerIssuerRef:
          group: cert-manager.io
          kind: ClusterIssuer
          name: hubble-ca-issuer
    relay:
      enabled: true
    ui:
      enabled: true
    metrics:
      enabled:
        - dns
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
